<script type='text/javascript'>
// Back to top
jQuery(document).ready(function(e){var t=e(&quot;#backtotop&quot;);e(window).scroll(function(){e(this).scrollTop()&gt;=1200?t.show(10).animate({opacity:&quot;1&quot;},10):t.animate({opacity:&quot;0&quot;},10)});t.click(function(t){t.preventDefault();e(&quot;html,body&quot;).animate({scrollTop:0},400)})})
//<![CDATA[
$(document).on("click",".share-toggle",function(){var e=$(this);e.toggleClass("toggle-active"),e.siblings(".share").toggleClass("share-active")});
// Share Button
var siteurl=window.location.href;document.write('<div class="sharebrow"><div class="sharede"> <a class="gp social-popup" href="https://plus.google.com/share?url='+siteurl+'" target="_blank" title="Share to Google+">    <i class="fa fa-google-plus gotea"></i> Google</a> <a class="fb social-popup" href="https://www.facebook.com/sharer/sharer.php?u='+siteurl+'" target="_blank" title="Share to Facebook">    <i class="fa fa-facebook fbtea"></i> Facebook</a> <a class="tw social-popup" href="https://twitter.com/intent/tweet?text='+encodeURIComponent(document.title)+"&url="+siteurl+'" target="_blank" title="Share to Twitter">    <i class="fa fa-twitter twtea"></i> Twitter</a>     <span class="pl" data-target="#share-menu"><i class="fa fa-plus plustea"></i> More</span> <ul class="dropdown-menu" id="share-menu">     <li><a class="social-popup" href="//www.digg.com/submit?url='+siteurl+'" target="_blank" title="Share This On Digg">Digg</a></li>     <li><a class="social-popup" href="//www.linkedin.com/shareArticle?mini=true&amp;url='+siteurl+'" target="_blank" title="Share This On Linkedin">Linkedin</a></li>     <li><a class="social-popup" href="//www.stumbleupon.com/submit?url='+siteurl+"&amp;title="+encodeURIComponent(document.title)+'" target="_blank" title="Share This On Stumbleupon">Stumbleupon</a></li>     <li><a class="social-popup" href="//delicious.com/post?url='+siteurl+"&amp;title="+encodeURIComponent(document.title)+'" target="_blank" title="Share This On Delicious">Delicious</a></li>     <li><a class="social-popup" href="http://www.tumblr.com/share/link?url='+siteurl+"&name="+encodeURIComponent(document.title)+"&description="+encodeURIComponent(document.title)+'" target="_blank" title="Share This On Tumblr">Tumblr</a></li></ul> </div><div class="clear"></div></div> '),$(document).ready(function(){$(".pl").click(function(){$("#share-menu").slideToggle("fast")})});
//Related Post
function saringtags(r,l){for(var e=r.split("<"),n=0;n<e.length;n++)-1!=e[n].indexOf(">")&&(e[n]=e[n].substring(e[n].indexOf(">")+1,e[n].length));return e=e.join(""),e=e.substring(0,l-1)}function relpostimgcuplik(r){for(var l=0;l<r.feed.entry.length;l++){var e=r.feed.entry[l];reljudul[relnojudul]=e.title.$t,postcontent="","content"in e?postcontent=e.content.$t:"summary"in e&&(postcontent=e.summary.$t),relcuplikan[relnojudul]=saringtags(postcontent,numchars),"media$thumbnail"in e?postimg=e.media$thumbnail.url:postimg="http://1.bp.blogspot.com/-htG7vy9vIAA/Tp0KrMUdoWI/AAAAAAAABAU/e7XkFtErqsU/s1600/grey.GIF",relgambar[relnojudul]=postimg;for(var n=0;n<e.link.length;n++)if("alternate"==e.link[n].rel){relurls[relnojudul]=e.link[n].href;break}relnojudul++}}function contains(r,l){for(var e=0;e<r.length;e++)if(r[e]==l)return!0;return!1}function artikelterkait(){for(var r=new Array(0),l=new Array(0),e=new Array(0),n=new Array(0),t=0;t<relurls.length;t++)contains(r,relurls[t])||(r.length+=1,r[r.length-1]=relurls[t],l.length+=1,l[l.length-1]=reljudul[t],e.length+=1,e[e.length-1]=relcuplikan[t],n.length+=1,n[n.length-1]=relgambar[t]);reljudul=l,relurls=r,relcuplikan=e,relgambar=n;for(var t=0;t<reljudul.length;t++){var a=Math.floor((reljudul.length-1)*Math.random()),u=reljudul[t],i=relurls[t],o=relcuplikan[t],s=relgambar[t];reljudul[t]=reljudul[a],relurls[t]=relurls[a],relcuplikan[t]=relcuplikan[a],relgambar[t]=relgambar[a],reljudul[a]=u,relurls[a]=i,relcuplikan[a]=o,relgambar[a]=s}for(var g,m=0,d=Math.floor((reljudul.length-1)*Math.random()),c=d,h=document.URL;relmaxtampil>m&&(relurls[d]==h||(g="<li class='news-title clearfix'>",g+="<a href='"+relurls[d]+"' rel='nofollow' target='_top' title='"+reljudul[d]+"'><div class='overlayb'></div><img src='"+relgambar[d]+"' /></a>",g+="<a class='relinkjdulx' href='"+relurls[d]+"' target='_top'>"+reljudul[d]+"</a>",g+="<span class='news-text'>"+relcuplikan[d]+"</span>",g+="</li>",document.write(g),m++,m!=relmaxtampil))&&(d<reljudul.length-1?d++:d=0,d!=c););}var relnojudul=0,relmaxtampil=3,numchars=90,reljudul=new Array,relurls=new Array,relcuplikan=new Array,relgambar=new Array;
// Main Menu
var ww=document.body.clientWidth;$(document).ready(function(){$(".nav li a").each(function(){$(this).next().length>0&&$(this).addClass("parent")}),$(".slide-menu").click(function(e){e.preventDefault(),$(this).toggleClass("active"),$(".nav").toggle()}),adjustMenu()}),$(window).bind("resize orientationchange",function(){ww=document.body.clientWidth,adjustMenu()});var adjustMenu=function(){768>ww?($(".slide-menu").css("display","inline-block"),$(".slide-menu").hasClass("active")?$(".nav").show():$(".nav").hide(),$(".nav li").unbind("mouseenter mouseleave"),$(".nav li a.parent").unbind("click").bind("click",function(e){e.preventDefault(),$(this).parent("li").toggleClass("hover")})):ww>=768&&($(".slide-menu").css("display","none"),$(".nav").show(),$(".nav li").removeClass("hover"),$(".nav li a").unbind("click"),$(".nav li").unbind("mouseenter mouseleave").bind("mouseenter mouseleave",function(){$(this).toggleClass("hover")}))};
// Simple Tab
!function(t){"use strict";var e=function(e,a){var n=this;n.element=e,n.$element=t(e),n.tabs=n.$element.children(),n.options=t.extend({},t.fn.mtabs.defaults,a),n.current_tab=0,n.init()};e.prototype={init:function(){var t=this;t.tabs.length&&(t.build(),t.buildTabMenu())},build:function(){var e=this,a=e.options,n=a.tab_text_el,i=a.container_class;e.tab_names=[],e.$wrapper=e.$element.wrapInner('<div class="'+i+'" />').find("."+i),e.tabs.wrapAll('<div class="'+a.tabs_container_class+'" />'),e.tabs.each(function(a,i){var s,r=t(i),o=n;s=r.find(o).filter(":first").hide().text(),e.tab_names.push(s)}),t.isFunction(a.onReady)&&a.onReady.call(e.element)},buildTabMenu:function(){for(var e,a=this,n=a.options,i=n.tabsmenu_el,s=a.tab_names,r="<"+i+' class="'+n.tabsmenu_class+'">',o=0,l=s.length,p=function(){var t=arguments;return n.tmpl.tabsmenu_tab.replace(/\{[0-9]\}/g,function(e){var a=Number(e.replace(/\D/g,""));return t[a]||""})};l>o;o++)r+=p(o+1,s[o]);r+="</"+i+">",a.$tabs_menu=t(r).prependTo(a.$wrapper),e=a.$tabs_menu.find(":first")[0].nodeName.toLowerCase(),a.$tabs_menu.on("click",e,function(e){var n=t(this),i=n.index();a.show(i),e.preventDefault()}).find(":first").trigger("click")},show:function(e){var a=this,n=a.options,i=n.active_tab_class;a.tabs.hide().filter(":eq("+e+")").show(),a.$tabs_menu.children().removeClass(i).filter(":eq("+e+")").addClass(i),t.isFunction(n.ontabselect)&&e!==a.current_tab&&n.ontabselect.call(a.element,e),a.current_tab=e},destroy:function(){var t=this,e=t.options.tab_text_el;t.$tabs_menu.remove(),t.tabs.unwrap().unwrap(),t.tabs.removeAttr("style"),t.tabs.children(e+":first").removeAttr("style"),t.$element.removeData("mtabs")}},t.fn.mtabs=function(a,n){return this.each(function(){var i,s=t(this),r=s.data("mtabs");i="object"==typeof a&&a,r||s.data("mtabs",r=new e(this,i)),"string"==typeof a&&r[a](n)})},t.fn.mtabs.defaults={container_class:"tabs",tabs_container_class:"tabs-content",active_tab_class:"active-tab",tab_text_el:"h1, h2, h3, h4, h5, h6",tabsmenu_class:"tabs-menu",tabsmenu_el:"ul",tmpl:{tabsmenu_tab:'<li class="tab-{0}"><span>{1}</span></li>'},ontabselect:null}}(window.jQuery,window,document),$(".popular-posts ul li .item-snippet").each(function(){var t=$(this).text().substr(0,120),e=t.lastIndexOf(" ");e>10&&$(this).text(t.substr(0,e).replace(/[?,!\.-:;]*$/,"..."))}),document.getElementById("clipboard-c").appendChild(document.getElementById("box-clip"));//]]></script>
<b:if cond='data:blog.pageType != &quot;index&quot;'><script type='text/javascript'>
$(document).ready(function(){var e=$(&quot;a.blog-pager-older-link&quot;).attr(&quot;href&quot;);$(&quot;a.blog-pager-older-link&quot;).load(e+&quot; .post-title:first&quot;,function(){var e=$(&quot;a.blog-pager-older-link&quot;).text();$(&quot;a.blog-pager-older-link&quot;).text(e)});var r=$(&quot;a.blog-pager-newer-link&quot;).attr(&quot;href&quot;);$(&quot;a.blog-pager-newer-link&quot;).load(r+&quot; .post-title:first&quot;,function(){var e=$(&quot;a.blog-pager-newer-link:first&quot;).text();$(&quot;a.blog-pager-newer-link&quot;).text(e)})});
$(&quot;ul#related-summary li img&quot;).each(function(){$(this).attr(&quot;src&quot;,$(this).attr(&quot;src&quot;).replace(/\/s[0-9]+(\-c)?\//,&quot;/w140-h140-c/&quot;))});</script></b:if>
<script type='text/javascript'> $(function() {$(&#39;.PopularPosts img&#39;).attr(&#39;src&#39;, function(i, src) {return src.replace( &#39;s72-c&#39;, &#39;s140&#39; );});});
var disqus_shortname = &quot;fagam&quot;;
!function(){var e=document.createElement(&quot;script&quot;);e.type=&quot;text/javascript&quot;,e.async=!0,e.src=&quot;//&quot;+disqus_shortname+&quot;.disqus.com/blogger_item.js&quot;,(document.getElementsByTagName(&quot;head&quot;)[0]||document.getElementsByTagName(&quot;body&quot;)[0]).appendChild(e)}();
function load_Comments(){var e=document.getElementById(&quot;disqusshow&quot;);e.style.display=&quot;none&quot;;var t=&quot;fagam&quot;;!function(){var e=document.createElement(&quot;script&quot;);e.type=&quot;text/javascript&quot;,e.async=!0,e.src=&quot;http://&quot;+t+&quot;.disqus.com/embed.js&quot;,(document.getElementsByTagName(&quot;head&quot;)[0]||document.getElementsByTagName(&quot;body&quot;)[0]).appendChild(e)}()}</script>
